[project]
name = "bept"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.2",
    "pandas>=2.2.2",
    "rich>=13.8.0",
    "rich-click>=1.8.3",
    "beaupy>=3.9.2",
    "pdb2pqr>=3.6.2",
    "tabulate>=0.9.0",
]
